pub mod adapter;
pub mod types;
mod telegram;
mod discord;
mod slack;
mod whatsapp;
mod signal;
mod matrix;
mod teams;
mod webhook;
mod qqbot;
mod wecom;
mod feishu;
mod dingtalk;

pub use adapter::{ChannelAdapter, AdapterFactory, PlatformMessage, PlatformConfig};
pub use types::{ChannelType, ChannelAccount};
pub use telegram::TelegramAdapter;
pub use discord::DiscordAdapter;
pub use slack::SlackAdapter;
pub use whatsapp::WhatsAppAdapter;
pub use signal::SignalAdapter;
pub use matrix::MatrixAdapter;
pub use teams::TeamsAdapter;
pub use webhook::WebhookAdapter;
pub use qqbot::QQBotAdapter;
pub use wecom::WeComAdapter;
pub use feishu::FeishuAdapter;
pub use dingtalk::DingTalkAdapter;
